### ISSUE TITLE
Any games using Acid ? 

### ISSUE THREAD

**Issue by ThinkalVB** [Equilibrium-Games/Acid#16]
Hai, I am a c++ programmer (beginner - moderate), I wish to know how rigid is this game engine ?. I tried to build a game engine of my own a 2D engine to precise however due to lack of contributions I have to drop it. I am now planning to focus on games instead of engines. However good works bros - keep it up. 
thinkalvb@gmail.com  https://github.com/ThinkalVB/NearEarth

**Comment by mattparks** [comment]
Hello, currently I am working some of the last kinks out of Acid while implementing new features. Acid compiles and runs on Windows, Linux, and MacOS between different releases and compilers. The only significant factor contributing to if Acid will run is platform Vulkan/Metal support. Developing a game engine is no small task, Acid was just me learning Vulkan and graphics programming. Acid is currently not running any games besides my side project of https://github.com/Equilibrium-Games/Microverse; however, I do have plans to use it in the future. If you have no issues with Acid please refrain from opening issues, if you have questions or comments you can email me at mattparks5855@gmail.com

**Comment by ThinkalVB** [comment]
I didn't find the email at first, it was dumb - sorry. Note taken. Yep, making a game is sort of a big pain.... Without a team, I am doomed. So not going behind a game without a team for now.
