### ISSUE TITLE
[VCPP2017] Runtime crash due to dynamic_cast of m_dynamicsWorld

### ISSUE THREAD

**Issue by lhog** [Equilibrium-Games/Acid#23]
Hi!

I'm trying to run Microverse and getting runtime crush in attempt to execute
`auto softDynamicsWorld = dynamic_cast<btSoftRigidDynamicsWorld *>(m_dynamicsWorld.get());` in `ScenePhysics::ScenePhysics() :`. Crash message is the following:
`Exception thrown at 0x00007FF8448C6727 (vcruntime140d.dll) in Microverse.exe: 0xC0000005: Access violation reading location 0x0000000000000004.`

If I replace`dynamic_cast` with `static_cast` here and in the body of `void ScenePhysics::SetAirDensity(const float &airDensity)` I'm able to run the game successfully.

Is this a known issue?

**Comment by mattparks** [comment]
I have no idea why it needs to use a static_cast for m_dynamicsWorld, but is fixed now.
