### ISSUE TITLE
some errors when using clang complie

### ISSUE THREAD

**Issue by fl0at88** [Equilibrium-Games/Acid#34]
/usr/bin/../lib64/gcc/x86_64-suse-linux/8/../../../../include/c++/8/optional:567:9: error: call to implicitly-deleted copy constructor of
      'std::_Optional_payload<acid::Transform, true, false, false>'
      : _Optional_payload(__engaged ?
        ^                 ~~~~~~~~~~~
/usr/bin/../lib64/gcc/x86_64-suse-linux/8/../../../../include/c++/8/optional:733:4: note: in instantiation of member function
      'std::_Optional_payload<acid::Transform, true, false, false>::_Optional_payload' requested here
        : _M_payload(__other._M_payload._M_engaged,
          ^
/usr/bin/../lib64/gcc/x86_64-suse-linux/8/../../../../include/c++/8/optional:985:11: note: in instantiation of member function
      'std::_Optional_base<acid::Transform, false, false>::_Optional_base' requested here
    class optional
          ^
/home/fl0at/Git/Acid/Sources/Uis/UiObject.hpp:122:63: note: in implicit copy constructor for 'std::optional<acid::Transform>' first required here
                std::optional<Transform> GetWorldTransform() const { return m_worldTransform; }
                                                                            ^
/usr/bin/../lib64/gcc/x86_64-suse-linux/8/../../../../include/c++/8/optional:581:7: note: explicitly defaulted function was implicitly deleted here
      _Optional_payload(const _Optional_payload&) = default;
      ^
/usr/bin/../lib64/gcc/x86_64-suse-linux/8/../../../../include/c++/8/optional:622:24: note: copy constructor of '_Optional_payload<acid::Transform, true,
      false, false>' is implicitly deleted because variant field '_M_payload' has a non-trivial copy constructor
          _Stored_type _M_payload;

**Comment by mattparks** [comment]
UiObject accidental had copying allowed causing the error above, bce5078e5dd6082008b3f43ea2cc2d10bed727be should have fixed that error. Let me know in this issue if you have other issues in Suse Linux while compiling.
