### ISSUE TITLE
Ubuntu Freetype2 Includes

### ISSUE THREAD

**Issue by mattparks** [Equilibrium-Games/Acid#42]
I have only encounted this problem on Debian and Ubuntu (not encountered on Arch), but when looking for system Freetype2 installs the includes cannot be found on these systems https://github.com/Equilibrium-Games/Acid/blob/9c64328e222ddceb0c98d59f58b13887f8ff0fcb/CMakeLists.txt#L70

```
/home/travis/build/Equilibrium-Games/Acid/Sources/Fonts/FontType.cpp:5:10: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>
```

**Comment by FirstLoveLife** [comment]
Is this a cmake issue? maybe cmake from ppa is older than aur? find_package will look for `FindFreetype`, which is located `/usr/share/cmake-3.13/Modules/FindFreetype.cmake` on my manjaro(arch-based dtor). 

I'm not sure about ubuntu/debain's package management, but you can try `pip install cmake`, which will also provide the latest cmake for you

**Comment by sum01** [comment]
I see you still have `find_package(Freetype)` commented out, even though the new merge made it `QUIET`. It could be uncommented since you're not using `REQUIRED`.

**Comment by mattparks** [comment]
But what happens if Freetype is found on some Linux platforms is `FREETYPE_INCLUDE_DIRS` does not include any valid includes, one way that has been said to be done is linking the includes:
```
sudo ln -s /usr/include/freetype2/freetype /usr/include/freetype
```
But in my last tests this did not help. I'm not getting this on my Arch system but I am on my Ubuntu 18.10 system (and Travis builds).

**Comment by sum01** [comment]
Oh, that's weird. Did you install `libfreetype6-dev` to get the Freetype headers?

**Comment by mattparks** [comment]
As of commit https://github.com/Equilibrium-Games/Acid/commit/bd3f96c479f793283b4f93f9a13e87f23a765f26 I switch Freetype on and logged the include dirs:
https://travis-ci.org/Equilibrium-Games/Acid/jobs/506539975#L876
https://travis-ci.org/Equilibrium-Games/Acid/jobs/506539975#L1288
I'm using this FindFreetype for analysis: https://github.com/Kitware/CMake/blob/master/Modules/FindFreetype.cmake
So it appears two includes are found, I don't think my link command changes anything, maybe the semi-colon in the path is causing issues?

**Comment by sum01** [comment]
The semi-colon is a delimiter in Cmake. So those are just read as two paths, not one long one.

As for that second thing you linked, the only thing that stands out is that the includes should be `#include <freetype2/ft2build.h>`, but I just tried building and it didn't matter (on Arch).

Maybe Ubuntu messes with the file structure or file names on Freetype2? Not sure.
