### ISSUE TITLE
Would you like to accept to replace git submodule with cmake's FetchContent?

### ISSUE THREAD

**Issue by FirstLoveLife** [Equilibrium-Games/Acid#49]
https://cmake.org/cmake/help/v3.11/module/FetchContent.html

Acid uses many git submodules https://github.com/Equilibrium-Games/Acid/blob/master/.gitmodules

So cmake's FetchContent can be very useful, as explained in this post: https://www.reddit.com/r/cpp/comments/9284h5/dependency_management_with_cmake_and_git/e33xxh2/

Besides, with the help of FetchContent, we can avoid clone libraries that have been already installed on local, which is not doable via git submodule.

As a cmake project(and all the libraries used by acid are also cmake-based), imo it'll be good to make use of cmake's feature. 

The only requirement is FetchContent requires cmake 3.11, but latest cmake(3.13 now) can be installed convinently via pip(pip install cmake).

**If you would like to accept FetchContent  and drop git submodule, I am very willing to make a pr.(if you are not sure about the effect of the feature and want to see before deciding, feel free to tell me, I'll also make a pr)**

**Comment by mattparks** [comment]
This would be a interesting way for removing annoying submodules, my only concern would be CMake support being very new. CI would need to use a newer CMake version if they are not already, and opening in Visual Studio may break. I will have to look at if the potential problems, but this sounds like a great idea.

**Comment by mattparks** [comment]
I currently have FetchContent working in all environments I have available to me as of this commit: https://github.com/Equilibrium-Games/Acid/commit/1a7f2fbbef7a572f65191150ffcfd33670268dfd
