### ISSUE TITLE
Why not use sdl for windowing to more easily target android? 

### ISSUE THREAD

**Issue by GeraldNebs** [Equilibrium-Games/Acid#57]

**Comment by mattparks** [comment]
I was opposed to using SDL a few months back because I assumed it was bloated and outdated. After looking at it for a while I think it would not be a bad idea to switch from GLFW to SDL. I'll only be using the window creation and no SDL audio, hopefully I can have something good working soon.

**Comment by GeraldNebs** [comment]
Okay. Thanks for the reply
